src/main/java/com/hart/HartApplication.java
src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/controller/cart/TestOrderController.java
src/main/java/com/hart/domain/CartInsertDTO.java
src/main/java/com/hart/mapper/CartMapper.java
src/main/java/com/hart/service/cart/CartService.java
src/main/java/com/hart/service/cart/CartServiceImpl.java
src/main/resources/mapper/CartMapper.xml
src/main/resources/templates/order/package.json
src/main/resources/templates/order/qr.html
src/main/resources/templates/order/shopping-cart.html
src/main/resources/templates/order/test.html
src/test/java/com/hart/zuik/mapper/CartMapperTests.java
src/test/java/com/hart/zuik/service/CartServiceTests.java

장바구니 INSERT 구현 중

---

pom.xml
src/main/java/com/hart/controller/cart/CartController.java
src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/domain/cart/CClassDTO.java
src/main/java/com/hart/domain/cart/CProductDTO.java
src/main/java/com/hart/domain/cart/CartDTO.java
src/main/java/com/hart/domain/cart/CartInsertDTO.java
src/main/java/com/hart/mapper/CartMapper.java
src/main/java/com/hart/service/cart/CartService.java
src/main/java/com/hart/service/cart/CartServiceImpl.java
src/main/resources/mapper/CartMapper.xml
src/main/resources/templates/cart/mycart.html
src/test/java/com/hart/zuik/controller/CartApiControllerTests.java
src/test/java/com/hart/zuik/mapper/CartMapperTests.java
src/test/java/com/hart/zuik/service/CartServiceTests.java

장바구니 생성 및 불러오기 기능 구현

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/domain/liveClass/LiveClassListDTO.java
src/main/java/com/hart/mapper/LiveClassMapper.java
src/main/java/com/hart/service/liveClass/LiveClassService.java
src/main/java/com/hart/service/liveClass/LiveClassServiceImpl.java
src/main/resources/mapper/LiveClassMapper.xml
src/main/resources/mapper/ProductsMapper.xml
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/liveClass/liveClassList.html
src/test/java/com/hart/ham/TestHam.java
src/test/java/com/hart/ham/controller/LiveClassControllerTest.java
src/test/java/com/hart/ham/service/LiveClassServiceTest.java

0315 ham 라이브 클래스 목록

---

src/main/java/com/hart/controller/cart/CartController.java
src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/controller/cart/TestOrderController.java
src/main/java/com/hart/controller/member/MemberController.java
src/main/java/com/hart/domain/member/ClubAuthMemberDTO.java
src/main/java/com/hart/domain/member/ClubMember2.java
src/main/java/com/hart/domain/share/ShareDTO.java
src/main/java/com/hart/mapper/CartMapper.java
src/main/java/com/hart/mapper/ShareMapper.java
src/main/java/com/hart/security/SecurityConfig.java
src/main/java/com/hart/service/ClubOAuth2UserDetailsService.java
src/main/java/com/hart/service/cart/CartService.java
src/main/java/com/hart/service/cart/CartServiceImpl.java
src/main/java/com/hart/service/share/ShareService.java
src/main/java/com/hart/service/share/ShareServiceImpl.java
src/main/resources/mapper/CartMapper.xml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/ShareMapper.xml
src/main/resources/templates/cart/sharecart.html
src/main/resources/templates/order/qr.html
src/main/resources/templates/order/test.html
src/test/java/com/hart/zuik/controller/CartApiControllerTests.java
src/test/java/com/hart/zuik/mapper/CartMapperTests.java
src/test/java/com/hart/zuik/mapper/ShareMapperTests.java
src/test/java/com/hart/zuik/service/CartServiceTests.java
src/test/java/com/hart/zuik/service/ShareServiceTests.java

공유 장바구니 시도 중

---

src/main/java/com/hart/controller/event/EventController.java
src/main/java/com/hart/controller/event/UploadController.java
src/main/resources/templates/event/upload.html
src/main/resources/templates/member/login.html

이벤트 업로드 페이지 추가

---

src/main/resources/templates/event/upload.html

업로드 페이지 사진 미리보기 및 추가 버튼 클릭시 모달 창 open/close기능

---

pom.xml
src/main/java/com/hart/controller/cart/CartController.java
src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/domain/share/SseEmitters.java
src/main/java/com/hart/mapper/ShareMapper.java
src/main/java/com/hart/service/share/ShareService.java
src/main/java/com/hart/service/share/ShareServiceImpl.java
src/main/resources/mapper/ShareMapper.xml
src/main/resources/templates/cart/checkout.html
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/cart/share.html
src/test/java/com/hart/zuik/mapper/ShareMapperTests.java
src/test/java/com/hart/zuik/service/ShareServiceTests.java

공유 장바구니 SSE 적용

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/mapper/LiveClassMapper.java
src/main/java/com/hart/service/liveClass/LiveClassService.java
src/main/java/com/hart/service/liveClass/LiveClassServiceImpl.java
src/main/resources/mapper/LiveClassMapper.xml
src/main/resources/static/css/style.css
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/liveClass/liveClassList.html

0316 ham 라이브 클래스 상세

---

src/main/java/com/hart/controller/cart/CartController.java
src/main/java/com/hart/controller/event/UploadController.java
src/main/java/com/hart/mapper/EventMapper.java
src/main/java/com/hart/service/event/EventService.java
src/main/java/com/hart/service/event/EventServiceImpl.java
src/main/resources/mapper/EventMapper.xml
src/main/resources/templates/event/upload.html

레시피 등록 페이지 수정 및 재료검색 기능

---

src/main/java/com/hart/controller/ProductRestController.java
src/main/java/com/hart/controller/ProductsController.java
src/main/java/com/hart/domain/ProductsVO.java
src/main/java/com/hart/mapper/ProductsMapper.java
src/main/java/com/hart/service/ProductsService.java
src/main/java/com/hart/service/ProductsServiceImple.java
src/main/resources/mapper/ProductsMapper.xml
src/main/resources/templates/product/productDetail.html
src/main/resources/templates/product/productList.html

img service 추가

---

src/main/resources/templates/cart/share.html
src/main/resources/templates/index.html

0317 CUSTOM ALERT 추가

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/resources/templates/liveClass/liveClassChatTestStream.html
src/main/resources/templates/liveClass/liveClassTestStream.html

0317 ham 라이브 채팅 개발용 구현

---

src/main/java/com/hart/HartApplication.java
src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/controller/liveClass/LiveClassRestController.java
src/main/resources/templates/liveClass/test.html

0323 ham liveClass 링크 연결

---

src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/domain/member/ClubAuthMemberDTO.java
src/main/java/com/hart/domain/member/ClubMember2.java
src/main/java/com/hart/domain/order/OrderTotalDTO.java
src/main/java/com/hart/domain/order/PinfoDTO.java
src/main/java/com/hart/domain/share/SseEmitters.java
src/main/java/com/hart/mapper/OrderMapper.java
src/main/java/com/hart/security/SecurityConfig.java
src/main/java/com/hart/security/handler/LoginSuccessHandler.java
src/main/java/com/hart/service/ClubOAuth2UserDetailsService.java
src/main/java/com/hart/service/order/OrderServiceImpl.java
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/OrderMapper.xml
src/main/resources/static/js/sse.js
src/main/resources/templates/cart/group.html
src/main/resources/templates/cart/share.html
src/main/resources/templates/includes/footer.html
src/main/resources/templates/includes/headTag.html
src/main/resources/templates/includes/header.html
src/main/resources/templates/order/checkout.html
src/main/resources/templates/product/productDetail.html

0324 SSE 문제 해결 및 주문 기능 구현 중

---

src/main/resources/templates/event/event.html
src/main/resources/templates/event/upload.html
src/main/resources/templates/event/vote.html

투표 페이지 추가 

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/controller/liveClass/LiveClassRestController.java
src/main/java/com/hart/domain/ProductlistTopVO.java
src/main/java/com/hart/domain/liveClass/MyLiveClassInfoDTO.java
src/main/java/com/hart/domain/liveClass/TestDomain123.java
src/main/java/com/hart/mapper/LiveClassMapper.java
src/main/java/com/hart/service/liveClass/LiveClassService.java
src/main/java/com/hart/service/liveClass/LiveClassServiceImpl.java
src/main/resources/mapper/LiveClassMapper.xml
src/main/resources/templates/liveClass/test.html
src/test/java/com/hart/ham/service/LiveClassServiceTest.java

[0324] ham mypageLiveClass 추가

---

src/main/java/com/hart/controller/member/MemberController.java
src/main/java/com/hart/controller/order/OrderController.java
src/main/java/com/hart/domain/member/ClubAuthMemberDTO.java
src/main/java/com/hart/domain/member/ClubMember2.java
src/main/java/com/hart/mapper/OrderMapper.java
src/main/java/com/hart/service/order/OrderServiceImpl.java
src/main/java/com/hart/service/share/ShareServiceImpl.java
src/main/resources/static/css/cart.css
src/main/resources/static/css/main1.css
src/main/resources/static/css/main2.css
src/main/resources/static/css/mypage.css
src/main/resources/static/css/order-complete.css
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/includes/headTag.html
src/main/resources/templates/includes/header.html
src/main/resources/templates/member/orderlist.html
src/main/resources/templates/order/complete.html

0327 페이지 추가 및 트리거 변경

---

src/main/java/com/hart/mapper/OrderMapper.java

Order Mapper 변경

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/domain/liveClass/LiveClassVedioDTO.java
src/main/java/com/hart/service/liveClass/LiveClassService.java
src/main/resources/templates/includes/header.html
src/main/resources/templates/liveClass/liveClassList.html
src/main/resources/templates/liveClass/liveClassVideo.html

[0327 vod 페이지 추가]

---

src/main/resources/static/css/font.css
src/main/resources/static/css/liveclass-detail1.css
src/main/resources/static/css/liveclass-detail2.css
src/main/resources/static/css/liveclass1.css
src/main/resources/static/css/liveclass2.css
src/main/resources/templates/liveClass/liveClassDetail.html

[0328] ham liveClassDetail 수정

---

src/main/java/com/hart/controller/order/OrderController.java
src/main/java/com/hart/controller/order/OrderRestController.java
src/main/java/com/hart/domain/order/OitemDTO.java
src/main/java/com/hart/domain/order/SearchResultDTO.java
src/main/java/com/hart/mapper/OrderMapper.java
src/main/java/com/hart/service/order/OrderService.java
src/main/java/com/hart/service/order/OrderServiceImpl.java
src/main/resources/mapper/OrderMapper.xml
src/main/resources/templates/member/orderlist.html
src/test/java/com/hart/zuik/controller/OrderApiControllerTests.java
src/test/java/com/hart/zuik/mapper/OrderMapperTests.java
src/test/java/com/hart/zuik/service/OrderServiceTest.java

0328 주문 내역 조회

---

src/main/java/com/hart/controller/order/OrderRestController.java
src/main/java/com/hart/service/order/OrderServiceImpl.java
src/main/resources/mapper/OrderMapper.xml
src/main/resources/static/js/cart.js
src/main/resources/static/js/share.js
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/includes/footer.html
src/main/resources/templates/includes/header.html
src/main/resources/templates/member/orderlist.html
src/main/resources/templates/member/tt.html
src/test/java/com/hart/zuik/service/OrderServiceTest.java

0329 주문내역 조회 완료

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/domain/liveClass/LiveClassDetailDTO.java
src/main/java/com/hart/domain/liveClass/LiveClassDetailInfoDTO.java
src/main/java/com/hart/domain/liveClass/LiveClassListDTO.java
src/main/java/com/hart/mapper/LiveClassMapper.java
src/main/java/com/hart/service/liveClass/LiveClassService.java
src/main/java/com/hart/service/liveClass/LiveClassServiceImpl.java
src/main/resources/mapper/LiveClassMapper.xml
src/main/resources/templates/liveClass/liveClassDetail.html
src/test/java/com/hart/ham/service/LiveClassServiceTest.java

[0329] ham liveClassDetail 완료

---

src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/domain/order/RecommandDTO.java
src/main/java/com/hart/domain/recommand/IngredientDTO.java
src/main/java/com/hart/domain/recommand/RecommandDTO.java
src/main/java/com/hart/domain/recommand/RliveClassDTO.java
src/main/java/com/hart/domain/recommand/RrecipeDTO.java
src/main/resources/mapper/CartMapper.xml
src/main/resources/mapper/ShareMapper.xml
src/main/resources/static/css/style.css
src/main/resources/static/js/cart.js
src/main/resources/static/js/order.js
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/cart/share.html
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/order/checkout.html
src/main/resources/templates/order/qr.html
src/main/resources/templates/product/productDetail.html

0331 장바구니 담은 후 추천 기능 구현 시도 중 

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/domain/liveClass/LiveClassListDTO.java
src/main/java/com/hart/domain/liveClass/MyLiveClassInfoDTO.java
src/main/java/com/hart/service/liveClass/LiveClassService.java
src/main/java/com/hart/service/liveClass/LiveClassServiceImpl.java
src/main/resources/mapper/LiveClassMapper.xml
src/main/resources/static/css/mypage.css
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/liveClass/liveClassList.html
src/main/resources/templates/liveClass/liveClassMypage.html
src/main/resources/templates/liveClass/liveClassVideo.html

[ham] 0331 liveClass mypage 구현 완료

[ham] 0331 liveClass mypage 구현 완료

---

src/main/java/com/hart/domain/recommand/RliveClassDTO.java
src/main/java/com/hart/service/liveClass/LiveSchedulerService.java
src/main/java/com/hart/service/recommand/RecommandServiceImpl.java
src/main/resources/mapper/RecommandMapper.xml
src/main/resources/static/js/cart.js
src/main/resources/static/js/dialog.js
src/main/resources/static/js/order.js
src/main/resources/templates/includes/footer.html
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/order/test.html
src/main/resources/templates/product/productDetail.html

장바구니 추천 기능 구현 후, 다이얼로그 구현 중

---

src/main/java/com/hart/service/liveClass/LiveClassServiceImpl.java
src/main/java/com/hart/service/liveClass/LiveSchedulerService.java
src/main/resources/templates/liveClass/liveClassList.html
src/main/resources/templates/liveClass/liveClassMypage.html

[0404] ham sms 알림 서비스

---

src/main/resources/mapper/ProductsMapper.xml
src/main/resources/mapper/RecipeMapper.xml
src/main/resources/templates/includes/header.html
src/main/resources/templates/product/productList.html
src/main/resources/templates/recipe/recipeDetails.html
src/main/resources/templates/recipe/recipeList.html

무한스크롤 구현완료

---

src/main/java/com/hart/controller/alarm/AlarmRestController.java
src/main/java/com/hart/controller/liveClass/LiveClassRestController.java
src/main/java/com/hart/domain/alarm/AlarmDTO.java
src/main/java/com/hart/mapper/AlarmMapper.java
src/main/java/com/hart/service/alarm/AlarmService.java
src/main/java/com/hart/service/alarm/AlarmServiceImpl.java
src/main/java/com/hart/service/alarm/NoticeService.java
src/main/java/com/hart/service/alarm/NotiveServiceImpl.java
src/main/resources/mapper/AlarmMapper.xml

[0404] ham notice Service 구현 완료

[0404] ham notice Service 구현 완료

---

src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/controller/order/OrderRestController.java
src/main/java/com/hart/service/order/OrderServiceImpl.java
src/main/resources/mapper/RecommandMapper.xml
src/main/resources/static/js/cart.js
src/main/resources/static/js/dialog.js
src/main/resources/static/js/share.js
src/main/resources/templates/cart/group.html
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/cart/share.html
src/main/resources/templates/includes/header.html
src/main/resources/templates/member/orderlist.html
src/main/resources/templates/order/test.html

다이얼로그에서 상품 내리기 완료

---

src/main/java/com/hart/controller/alarm/AlarmRestController.java
src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/controller/liveClass/LiveClassRestController.java
src/main/resources/mapper/AlarmMapper.xml
src/main/resources/static/css/alarm.css
src/main/resources/templates/liveClass/liveClassList.html
src/test/java/com/hart/ham/mapper/AlarmMapperTest.java

[0406] ham 알림 구현 1차

---

src/main/resources/static/css/style.css
src/main/resources/static/js/customAlert.js
src/main/resources/static/js/dialog.js
src/main/resources/templates/includes/footer.html
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/order/qr.html
src/main/resources/templates/product/productDetail.html

다이얼로그 및 QR 스캔 페이지 변경

---

src/main/java/com/hart/controller/alarm/AlarmRestController.java
src/main/java/com/hart/domain/alarm/NoticeDTO.java
src/main/java/com/hart/mapper/AlarmMapper.java
src/main/java/com/hart/service/alarm/NoticeService.java
src/main/java/com/hart/service/alarm/NotiveServiceImpl.java
src/main/resources/mapper/AlarmMapper.xml
src/main/resources/templates/includes/header.html
src/main/resources/templates/liveClass/liveClassList.html
src/test/java/com/hart/ham/mapper/AlarmMapperTest.java

[0406]ham 헤더 알림 추가

---

pom.xml
src/main/java/com/hart/HartApplication.java
src/main/resources/templates/cart/group.html
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/cart/share.html
src/main/resources/templates/event/event.html
src/main/resources/templates/event/upload.html
src/main/resources/templates/event/vote.html
src/main/resources/templates/event/voteDetail.html
src/main/resources/templates/index.html
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/liveClass/liveClassList.html
src/main/resources/templates/liveClass/liveClassMypage.html
src/main/resources/templates/liveClass/liveClassVideo.html
src/main/resources/templates/liveClass/test.html
src/main/resources/templates/member/login.html
src/main/resources/templates/member/mypage.html
src/main/resources/templates/member/mypage_order_history.html
src/main/resources/templates/member/orderlist.html
src/main/resources/templates/order/checkout.html
src/main/resources/templates/order/complete.html
src/main/resources/templates/order/qr.html
src/main/resources/templates/product/productDetail.html
src/main/resources/templates/product/productList.html
src/main/resources/templates/product/productList2.html
src/main/resources/templates/recipe/recipeDetails.html
src/main/resources/templates/recipe/recipeList.html

배포로 인한 템플릿 경로 설정 

---

src/main/java/com/hart/controller/ProductsController.java
src/main/java/com/hart/controller/RecipeController.java
src/main/java/com/hart/controller/cart/CartController.java
src/main/java/com/hart/controller/member/MemberController.java
src/main/java/com/hart/controller/order/OrderController.java
src/main/resources/templates/product/productDetail.html

컨트롤로 경로 설정 및 배포 관련 문제 해결 중

---

src/main/java/com/hart/controller/cart/CartRestController.java
src/main/java/com/hart/controller/order/OrderRestController.java
src/main/java/com/hart/controller/recommand/RecommandRestController.java
src/main/java/com/hart/domain/order/SearchDTO.java
src/main/java/com/hart/security/SecurityConfig.java
src/main/java/com/hart/service/order/OrderServiceImpl.java
src/main/resources/mapper/OrderMapper.xml
src/main/resources/static/js/cart.js
src/main/resources/static/js/customAlert.js
src/main/resources/static/js/dialog.js
src/main/resources/static/js/share.js
src/main/resources/static/js/sse.js
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/cart/share.html
src/main/resources/templates/includes/footer.html
src/main/resources/templates/includes/header.html
src/main/resources/templates/index.html
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/member/orderlist.html
src/main/resources/templates/order/qr.html
src/main/resources/templates/product/productDetail.html
src/main/resources/templates/product/productList.html
src/main/resources/templates/recipe/recipeList.html

기능 점검 및 수정 중

---

src/main/java/com/hart/security/SecurityConfig.java
src/main/java/com/hart/security/handler/LoginSuccessHandler.java
src/main/resources/templates/includes/headTag.html
src/main/resources/templates/member/login.html

로그인 폼 오류 수정

---

src/main/resources/static/js/order.js
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/product/productDetail.html

클래스 상세 충돌 수정:

---

src/main/java/com/hart/controller/recommand/RecommandRestController.java
src/main/java/com/hart/mapper/RecipeMapper.java
src/main/java/com/hart/mapper/RecommandMapper.java
src/main/java/com/hart/service/order/OrderService.java
src/main/java/com/hart/service/order/OrderServiceImpl.java
src/main/java/com/hart/service/recommand/RecommandService.java
src/main/java/com/hart/service/recommand/RecommandServiceImpl.java
src/main/resources/mapper/OrderMapper.xml
src/main/resources/mapper/RecommandMapper.xml
src/main/resources/static/css/style.css
src/main/resources/static/js/dialog.js
src/main/resources/templates/cart/mycart.html
src/main/resources/templates/cart/share.html
src/main/resources/templates/includes/footer.html
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/liveClass/liveClassList.html
src/main/resources/templates/member/orderlist.html
src/main/resources/templates/order/checkout.html
src/main/resources/templates/order/complete.html
src/main/resources/templates/product/productDetail.html
src/main/resources/templates/product/productList.html
src/main/resources/templates/product/shop.html
src/main/resources/templates/recipe/recipeDetails.html
src/main/resources/templates/recipe/recipeList.html
src/test/java/com/hart/zuik/mapper/RecommandMapperTests.java
src/test/java/com/hart/zuik/service/RecommandServiceTests.java

다이얼로그 수정 ~

---

src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/domain/liveClass/LiveClassRegisterDTO.java
src/main/java/com/hart/mapper/LiveClassMapper.java
src/main/java/com/hart/service/liveClass/LiveClassService.java
src/main/java/com/hart/service/liveClass/LiveClassServiceImpl.java
src/main/resources/mapper/LiveClassMapper.xml
src/main/resources/static/css/alarm.css
src/main/resources/static/css/mypage.css
src/main/resources/templates/includes/footer.html
src/main/resources/templates/includes/header.html
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/member/orderlist.html
src/test/java/com/hart/ham/mapper/AdminMapperTest.java
src/test/java/com/hart/ham/mapper/LiveClassMapperTest.java

[0411] ham 프론트 부분 1차 합병

---

src/main/resources/static/js/dialog.js

다이얼로그 삭제 추가

---

src/main/java/com/hart/controller/recommand/RecommandRestController.java
src/main/java/com/hart/service/recommand/RecommandService.java
src/main/java/com/hart/service/recommand/RecommandServiceImpl.java
src/main/resources/mapper/RecommandMapper.xml
src/main/resources/static/js/dialog.js
src/main/resources/templates/liveClass/liveClassDetail.html
src/main/resources/templates/member/login.html
src/main/resources/templates/order/checkout.html
src/main/resources/templates/product/productDetail.html

추천 기능 상세 구현

---

src/main/java/com/hart/controller/ProductRestController.java
src/main/java/com/hart/controller/ProductsController.java
src/main/java/com/hart/service/ProductsServiceImple.java
src/main/resources/mapper/ProductsMapper.xml
src/main/resources/templates/product/productDetail.html
src/main/resources/templates/product/productList.html
src/main/resources/templates/recipe/recipeList.html

깃 합치기 팀원들과

---

src/main/resources/templates/liveClass/liveClassMypage.html
src/test/java/com/hart/zuik/service/RecommandServiceTests.java

[0412] ham 점심 멘토링 전

---

src/main/resources/templates/liveClass/liveClassMypage.html

[0413] ham 오전 커밋

---

src/main/java/com/hart/HartApplication.java
src/main/java/com/hart/controller/liveClass/LiveClassController.java
src/main/java/com/hart/domain/admin/PageDTO.java
src/main/java/com/hart/security/SecurityConfig.java
src/main/resources/templates/index.html

CORS 설정 변경

---

src/main/resources/static/css/dialog.css
src/main/resources/templates/product/productDetail.html
src/main/resources/templates/product/productList.html

다이아로그 css건드림

---

src/main/resources/templates/includes/header.html
src/main/resources/templates/index.html

메인 페이지 충돌 수정

---

src/main/resources/static/js/dialog.js

추천 다이얼로그 수정
